# transcript generation

import requests

url = "http://127.0.0.1:5000/transcript"
data = {"youtube_link": "https://www.youtube.com/watch?v=zC6B490i-IY&t=423s"}

response = requests.post(url, json=data)
print(response.json())  # Should return the transcript

# # summarty generation

# import requests

# url = "http://127.0.0.1:5000/summarize"
# data = {
#     "youtube_link": "https://www.youtube.com/watch?v=YvJ4C08pFJQ&t=1s",
#     "word_count": 100
# }

# response = requests.post(url, json=data)
# print(response.json())

# # chatbot interaction
# # you can chat with summary
# # if you want to chat with transcript of video just put transcript instead of summary but keep in mind parameter should be summary

# import requests

# url = "http://127.0.0.1:5000/ask"
# data = {
#     "user_input": "What is the main topic of the video?",
#     "summary": """
#     hello guys so one of the most common question that has been asked from past 2 to three months because the way that I specifically upload videos related to generative AI or any new things that are actually coming in the market or specifically that is happening in the field of AI how do I make sure that I stay updated with all this relevant information uh this is what I'm actually going to talk about uh this was one of the most requested video I think probably I've seen 10 to 15 videos where many people have written down in the comment in the comment section Kish how do you stay relevant how do you stay updated with all the things that are happening in the field of AI so let me talk about this um see guys in my in my day like what I actually do as soon as I probably get up in the morning uh uh 
# 10:00 9:45 to 10:00 right I usually come and sit uh in my workstation uh and uh what I do is that I follow some strategies you know what what all things I really need to be updated at because that is how I my day starts everything every day some new things are actually coming up one or the other things are actually happening let it be in the research field the companies are coming up with new things in the field of AI someone is generating some amazing llm models 
# inferencing engines many more things and again uh I definitely like to stay updated with all this information so that uh you know uh and I also try to see that where this specific thing can create an impact in Industry also and based 
# on that I plan my entire videos specifically in the YouTube channel so that it'll be definitely Ely helpful for you and you will also be staying relevant uh with respect to the industry that you really want to work with because everything that I probably upload in my main channel is with respect to the recent research that are probably going on right so considering this let me just give you a brief idea like today also today morning uh at 10:00 again I sat I went 
# through multiple things what all things I usually go ahead with all those things I will be discussing ahead so please make sure that you watch this video till the end because you will also get an idea with respect to like what how do 
# I stay relevant how do I make sure that I have all the knowledge regarding AI around me okay so the first thing is that uh first of all you really need to identify companies who are specifically working in the field of generative AI or AI machine learning anything so bigger companies like Google meta so here you can see Meta is also there anthropic 
# is also there Microsoft is also there um llama meta Lama is also there hugging face is also there Alpha signal I'll also be talking about this particular website this is not a paid promotion of any of this things you know why do I follow this particular page also I will be mentioning about so the first thing that I usually do is that uh I open all this particular page so in short these all pages are booked marked in my browser you know and uh what I do is that at 
# any point of time you know first my main thing is that I'll go ahead and see all these particular Pages what new things are probably coming up what is the new kind of development that is basically happening uh if you if you just go ahead and see in blogs right Google AI blogs if you just go and search Google ai. gooogle disover blogs you'll be able 
# to see new things that are probably coming up all the information will be over here and uh with respect to the kind of research specifically these bigger companies are doing some of the new things are actually coming up they just don't provide you something related to research but also some kind of practical implementation so I usually follow this kind of pages so similarly you can see Google is there open AI is there right if I probably give you an ID like what open is specifically doing with respect to the news and all I usually see this and uh since I already have an open API account and trust me open is doing tremendously well they also coming planning to come up with gb5 they also planning to come up with AGI so uh this is one of the most important thing that I usually see that what things they are specifically doing and some more products some more things are going to get developed soon in opena and based on that I also upload a lot of videos with respect to this uh so here also you can see with respect to Microsoft uh because I am planning to cover three important clouds AWS Google cloud and Azure uh because in most of the job requirements that 
# is specifically required and if you don't know I've already uploaded an N toed project in AWS itself right uh so yeah in AWS by using AWS Bedrock so here also this is what is the blogs that I probably follow and if you don't know guys um uh again again this is not sponsored uh also try to get an access of this right so here you'll be able to see GitHub co-pilot workspace okay so try to get an excess of this because soon I'll also be coming up with this particular 
# tutorial amazing workspace you can really do a lot of things with respect to developing um projects and all so this is what I will be showing you how you can actually do this amazing thing so GitHub is also coming up with GitHub co-pilot worksspace with respect to development it will be must but again uh as we go ahead I'll be showing you how we can actually work on projects over there so as said uh most of the company website I usually see let mistr let it be hugging face what all new models are specifically coming how to use this particular model so you see I was just checking out with Nvidia with respect to this check text generation using Lama 3 chat QA right and here also you'll be able to see you'll be able to see how you can actually Implement all these things and all what is accuracy and all that all are there along with the code everything you'll be able to find out and hugging face is one of the most popular Library so I'll also be creating a crash course with respect to hugging face and generative AI so um I think just in some days I'll do be doing that also here you can can probably see I stay up to date all with respect to all the models that are probably coming in hugging face so that I can use it for multiple use cases um meta I've already told you other than that now these are most of the pages that we I actually follow I just don't follow this also uh if you are also looking for job you should also follow the career page what it is specifically required what skill sets are actually required so if I say right over here let's say Google generative AI generative AI jobs career page right if I just search for it here you'll be able to see many things you'll be able to find out over here and different different location other than that you can directly go to google.com with respect to the job results you'll be able to get that information so just go ahead and try to see what kind of skill sets it is looking for so that you'll be able to prepare with so this is one other thing that I do the other thing is that I probably follow everybody's X account right so 
# here you'll be able to see Sam Altman right he's from open Elon Musk and all I usually follow them a lot because we keep on posting some new things that is probably happening over there um any new thing that is probably coming any new announcement they have to do specifically to the product I stay up to date with respect to that and this is morning 
# 1 hour right 10 to 10:30 to 11:00 I usually do all these things and uh I also make sure that I keep a note of what all videos I also have to make right for you all and it's just not like announcement videos mostly towards how we can practically implement it so here also you can see anthropic they also coming up with some amazing llm models so I also follow their page page with respect to this so this is done blogs page this page X account and all one more thing like uh now when you're following this many number of pages right and whenever you open Google right let's say the Google search engine whenever you open you in your mobile phone only you'll be able to see a lot of feeds related to AI because Google understands that that hey you are probably looking for AI things that are probably coming up right so all upto-date feeds also automatically gets updated in our phone in my phone specifically now one more platform is this which is called as Alpha signal uh see again this is not a prid promotion but I found out this platform is amazing 
# uh just to get the summary what whatever updates are basically happening in the field of AI so here RCV is included GitHub Google Scholar open review from blogs social media experts all the information you know daily probably I get a 
# mail with respect to all the summary and the best thing is that in the morning time only I get the entire summary so 
# just you can go to this particular page go ahead and put your email ID and if you want you can check it out see today's uh it's most about this one some breakthrough that is probably happening in Transformers with parallel lstms now see all these kind of videos I've already uploaded and the best thing will be when you just read it you'll be able to 
# get lot of information see here you can see Helo protect hallucination firewalls open SE GPD might be shown next Monday together with gp4 light uh Google ands Alpha fold 3 so here just by seeing this right you get the most interesting news out there and if you probably want to just check it out you can go ahead and check it out in details right so mostly I've covered almost everything what I actually refer and at the end of the day you know I always keep make sure that I keep 1 hour space around in my time in my day-to-day activities for getting updated all these things again uh to get updated and to implement things what all things I specifically use again I focus more on vs code here you can probably see anything that is probably coming up in vs code I usually implement it I depend on lot of extensions that are specifically coming over here right I usually use a lot of extensions for my coding purpose um GitHub co-pilot 
# also access I've actually got uh from GitHub itself since I have a GitHub Star Award so that it helps me to work quickly and efficiently along with that I also maintain an Excel sheet with respect to the new things that are coming and I wait wait wait for uh the implementation purpose I'm very much excited for the implementation purpose and that is 
# how I specifically go ahead um yeah that's it you know uh but again lot of efforts is required in this here I've just shown you some of the other thing but understand reading each and every article understanding about it seeing the research paper if it is included over there all those things matters a lot right and that is how I usually go ahead uh 
# this is just an idea I know it's not such a big thing uh everybody probably does that so I just wanted to tell you that yeah this is what is I I follow and based on that new things also I do one more thing is that uh in YouTube I also make sure that I keep on serving what are the new things that are probably coming up in AI so they are foreign creators they are Indian creators some of the other thing they will keep on uploading I do follow them and definitely you 
# should also follow YouTubers um again I know they are doing some amazing work everybody's doing an amazing work try to give that kind of respect subscribe the channel and yes keep on supporting them this all it for my side I'll see you in the next video have a great day thank you one all take care bye-bye
#     """
# }

# response = requests.post(url, json=data)
# print(response.json())  # Should return AI-generated response

